### ISSUE TITLE
Error using 0.5.0

### ISSUE THREAD

**Issue by nk1tz** [Veriphi/veto-ui#12]
Just imported v`0.5.0` into project and getting this runtime error:
```
TypeError: Cannot read property '0' of undefined
    at modalStyles (/Users/me/Workspace/veriphi/node_modules/@veriphi/veto-ui/dist/veto-ui.cjs.development.js:132:42)
    at GlobalStyles (/Users/me/Workspace/veriphi/node_modules/@veriphi/veto-ui/dist/veto-ui.cjs.development.js:472:18)
```

**Comment by xdrdak** [comment]
Please consult the latest https://github.com/Veriphi/veto-ui#installing guide since it changed a bit in order to enable proper theme switching.
